### ISSUE TITLE
jQuery UI Dialog element being hidden by the backdrop highlight

### ISSUE THREAD

**Issue by chrome-brutus** [sorich87/bootstrap-tour#166]
Here is a jsFiddle example of what I mean: http://jsfiddle.net/FJPGL/1/

The highlight element should be behind the targeted element, but instead it is on top which hides the text.

I don't think this would be considered a bug with Bootstrap Tour since I think the issue is the z-index of the dialog, but it would be nice if it worked by default.

Has anyone else come across this, or have any recommended fix other than manually removing/adding the z-index on Tour start/end?

**Comment by acamilicko** [comment]
This fix doesn't work again. Seems like some change in bootstrap or bootstrap-tour again. Alex

**Comment by KyleMit** [comment]
@acamilicko, Ok, so the original fix worked for release 9.3.

I finally specified a version instead of going of trunk

[**Here's a stable working demo with Bootstrap-Tour 0.9.3**][1]

----

It looks like the problem with version 10.1 of Bootstrap-Tour was introduced with [this commit][4] which added `!important` to  `.tour-step-background {position: absolute;}`

If you want to reposition the elements in the DOM, you need to make sure the position is fixed, so you'll have to override like this:

```css
.tour-step-background {
    position: fixed !important;
}
```

[**Working Demo with Bootstrap-Tour 0.10.1 in Fiddle**][3]

----

Speaking of versions, it looks like Bootstrap 3.3+ broke Bootstrap tour.  The following code won't work with 3.3.0, but will if you change it to 3.2.0

```html
<div id="content">
    Hello, World!
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/css/bootstrap.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tour/0.10.1/css/bootstrap-tour.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tour/0.10.1/js/bootstrap-tour.js"></script>
```
```js
var tour = new Tour({
  steps : [{
    element: "#content",
    title: "Title of my step",
    content: "Content of my step"
  }]
});
tour.init()
tour.start();
```

[**Broken Demo with Bootstrap 3.3.0 in Fiddle**][2]

[1]: http://jsfiddle.net/KyleMit/DYNbj/80/
[2]: http://jsfiddle.net/KyleMit/DYNbj/81/
[3]: http://jsfiddle.net/KyleMit/DYNbj/82/
[4]: https://github.com/sorich87/bootstrap-tour/commit/a3ef42b1dbc3e18b11a3749c83d0d2034592fa79

**Comment by acamilicko** [comment]
Thank you, now works like a charm. Regards and Happy New Year!

**Comment by jcorreia** [comment]
I´ve tried various solutions and this almost worked, but the background in some doesnt show, and its clearing the backdrop in some other elements I dont want.
I´m using nav tabs.
I wish this could be fixed to work in bootstrap 3, it isnt at all...
thanks

**Comment by lucknerjb** [comment]
@KyleMit You're a fucking genius my friend. I've hacking at this for a while and perusing the issues for an answer. Good stuff - many thanks.

**Comment by goethewins** [comment]
I am having this problem now. Why hasn't this been integrated into the core code base? it has been over a year hasn't it. When will this be fixed? v0.10.2  ?

Please advise. I need something that works. Both this and intro.js have the same problem.

**Comment by goethewins** [comment]
@KyleMit  your solution works for 10.2 except hat if you scroll down it leaves the highlighted are on the page as a copy. hard to explain, but it is annoying. Anyone here get this to work without any bugs?

**Comment by melissahie** [comment]
I'm having this same issue. Will try to continue debugging.. in the mean time, if there is any solution it would be highly appreciated @KyleMit. Thanks!

**Comment by melissahie** [comment]
So I dug deeper into the issue I was having, which stemmed from upgrading from an old Bootstrap Tour version 0.4 to the latest 0.10.2

I discovered that in version 0.4 Bootstrap Tour used to do what was described by @KyleMit above, which was to insert the tour-backdrop in the same stack as the tour object. However in 0.10 tour-backdrop is being inserted at the end of the page as we all understand from this thread.

Would be interesting to know the history of why this was changed @sorich87?

**Comment by bcoover** [comment]
This fixes it, include these items in your own css file which is included after the bootstrap-tour.css file (overrides that):

.tour-step-background,
.tour-backdrop {
    position: fixed !important;
    z-index: 1191;
}

.tour-step-background {
    background: #fff;
}

.popover[class*="tour-"] {
  z-index: 1192;
}
