### ISSUE TITLE
Tour silently fails on steps where element uses "eq()" selector

### ISSUE THREAD

**Issue by skybondsor** [sorich87/bootstrap-tour#307]
I'm using ":contains()" as a workaround for now, but thought I'd alert you.

**Comment by skybondsor** [comment]
It's actually working for me now too! I have no idea what the problem was before.

**Comment by NikJaySix** [comment]
Literally spent hours on trying to fix this same problem, but it wasn't a problem with :eq specifically, it was because i didn't give the tour a unique name and it was stored in local storage with an incorrect selector. 

I had to randomly generate a string for the name so it is new each refresh. (only for development)
