### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by edu2004eu** [sorich87/bootstrap-tour#319]
Currently, the "Prev", "Next" and "End Tour" buttons can't be translated. Either pull them out of the template and make them configurable (preferably via `$.fn`), so that we can use our own translation mechanisms, or have a proprietary simple translation mechanism.

Please :)

**Comment by sorich87** [comment]
Closing due to lack of response.

**Comment by zorobabel** [comment]
@edu2004eu @cleyan You can use:

https://github.com/airbnb/polyglot.js

**Comment by diesl** [comment]
@sorich87, could you please reopen this issue?

> There is a template option that'll be backward compatible. I mean you could do:
> Let me know if there's any issue with this approach.

Your approach is not very DRY. Also, when the default template will change in a future update, it will not show up because it is overwritten with the old custom template. So you have to check for changes with every update.

The solution @edu2004eu proposed simply is a cleaner approach.

**Comment by diesl** [comment]
Best proof why manual checking for changes is not a good idea: The global options' template string on your [API documentation page](http://bootstraptour.com/api/) is outdated and does not show the current version.

**Comment by emanwebdev** [comment]
Hi all, today have you got the solution ?
