### ISSUE TITLE
Tour only starts when I open Chrome Dev Tool

### ISSUE THREAD

**Issue by edipofederle** [sorich87/bootstrap-tour#485]
Hi,

Something weird happen here, my tour only starts when I open the Chrome Dev Tool (e.g "inspect element").

My conde:
```
var resource = gon.resource
var action   = gon.action

var dashboard_index;

dashboard_index = new Tour({
 
  steps: [
    ...
  ]});

var guides = {
  "dashboard_index": dashboard_index
  .....
}

var tour = guides[resource + '_' + action]

tour.init();
tour.start();
```

**Version: bootstrap-tour - v0.10.1**

Thanks in advance.

**Comment by nrmohan** [comment]
Did you find any solution? Am having the same issue.

**Comment by edipofederle** [comment]
HI @nrmohan, Unfortunately not yet....

**Comment by saggiatoreblue** [comment]
@edipofederle  Not sure if this will help. But encountered a similar issue on our end, the cause was the markup referenced in steps wasn't loaded into the page until after an api call. The dev tool issue was because it triggers a window resize which I think causes the plugin to reevaluate. So maybe make sure the markup is there before the script is loaded.

**Comment by edipofederle** [comment]
@saggiatoreblue make sense. I will double check it soon. You think make sense keeping this issue open ?

**Comment by saggiatoreblue** [comment]
@edipofederle If you can confirm your issue is related to the dom elements being loaded after the plugin itself is initialized then I think maybe yes it could be closed. I haven't had a chance to look at the source to confirm above though. Just a suspicion at this point.

**Comment by edipofederle** [comment]
@saggiatoreblue yes, confirmed here. Thanks. I will close it.
