### ISSUE TITLE
Display of popup problematic and runs out of room displaying poorly

### ISSUE THREAD

**Issue by ocmobi** [sorich87/bootstrap-tour#506]
Popovers/tooltips can be dynamically placed meaning based on the where they end up in the window like too far right for example they can switch to being placed in the bottom using code.

placement: function (context, source) {
        var position = $(source).position();

        if (position.left > 515) {
            return "left";
        }

        if (position.left < 515) {
            return "right";
        }

        if (position.top < 110){
            return "bottom";
        }

        return "top";
    }

When a element is too wide the popover tries going beside it, this ends up being a really bad display as it doesn't try to overlap at all just squeeze beside it and it's too tiny.

I say there should be "overlap" options if there's not enough room, and dynamic placement options saying "best fit" or let us code something ourselves like above.  On the right is fine, but sometimes it has to be on the left (if something is on far right of page), or below if something is too wide and takes up whole page, so sometimes it can't always be the same.

This is definitely a display bug issue for me and I am having issues with i.

**Comment by ousram** [comment]
This issue was fixed since the last commit.
You can fix your problem in two ways : 
1 - While specifying your tour or your steps placement parameter, add the ''auto' option.
placement : "auto right", so when they are not enough space at right, the popover will show up at left.
placement : "auto left", so when they are not enough space at left, the popover will show up at right.
...........
2 - Set the smartPlacement parameter for your tour or for each step you want:
placement : 'left'
smartPlacement : true
