### ISSUE TITLE
Support Arabic

### ISSUE THREAD

**Issue by hawkiq** [sorich87/bootstrap-tour#511]
when I used this awesome plugin, I've noticed I cannot write in Arabic, can you make it support RTL   languages.
![tour wrong](https://cloud.githubusercontent.com/assets/7524502/12865878/e7b3860a-ccca-11e5-9838-a9ffe39bb4ef.png)

**Comment by ousram** [comment]
@sorich87 ?

**Comment by sorich87** [comment]
There seem to be two issues there:
1- your document doesn't seem to support the right charset. that's why the characters don't appear. check if you put the utf-8 meta tag in your code.
2- about the RTL issue. we're following Bootstrap lead. there's currently no out of the box support but you can easily add it in your CSS code. this seems to work for some people : http://stackoverflow.com/a/32281462
