### ISSUE TITLE
button are not displayed

### ISSUE THREAD

**Issue by Salut22** [sorich87/bootstrap-tour#535]
I am using your plugin but I have faced some issues. The button becomes completely white and I can not click it.
How can I fix the problem?.
I created a jsfiddle for mini example http://jsfiddle.net/wmf9y2pv/2/ . Thank you.

**Comment by rgalaxy** [comment]
i think it's because the `class="navbar-fixed-top"`, this tour still have some problem with fixed element, as far as i look maybe #183 could help you.
you need to play with the z-index of the content. 

sorry if i couldn't give you proper answer as me myself still new in this plugin, but it might able to help you

**Comment by sorich87** [comment]
See #183. A better solution is being worked on.
