### ISSUE TITLE
Popover max-width

### ISSUE THREAD

**Issue by adriangibbons** [sorich87/bootstrap-tour#637]
Hi, great project. Very easy to use and effective!

I'm trying to make some step popovers wider using CSS but can't get it to work.

It seems that Bootstrap defines max-width for popovers:
```css
.popover {
  ...
  max-width: 276px;
  ...
}
```

I've added a class to my own custom stylesheet (included after all other stylesheets):
```css
.popover-double-width {
  max-width: 552px !important;
}
```

I am then setting the HTML template option for the step to be:
```html
"<div class='popover popover-double-width tour'>
  <div class='arrow'></div>
  <h3 class='popover-title'></h3>
  <div class='popover-content'></div>
  <div class='popover-navigation'>
    <button class='btn btn-default' data-role='prev'>« Prev</button>
    <span data-role='separator'>|</span>
    <button class='btn btn-default' data-role='next'>Next »</button>
    <button class='btn btn-default' data-role='end'>End tour</button>
  </div>
</div>"
```
I only changed to the top line of the default string to include my double width class.

However when I start the tour and go the step that should be wider, it's the same width as the others and when I inspect the popover element in Chrome I do not see a reference to the double width class anywhere.

Am I doing something wrong? How should I make a popover wider?

Thanks in advance, Adrian.

**Comment by apennell** [comment]
Do you want it to be `max-width: 552px`, or do you actually want an exact width of 552px? In my case, I knew I wanted a popover with a width of 300px, so I did:
```js
{
    ...
    template: "<div class='popover tour project-tour'>\
        <div class='arrow'></div>\
        ...\
    </div>",
    ...
}
```

```css
.popover.tour.project-tour {
  max-width: none;
  width: 300px;
}
```

Using the slightly more specific CSS target of `.popover.tour.project-tour`, rather than just my custom class, gave me more specificity than that bootstrap CSS so I didn't need to use important. 

That being said, even if I replicate your conditions in mine I'm able to get it to work (`project-tour{ max-width: 552px !important;}` gives me a popover that's 552px wide).

**Comment by adriangibbons** [comment]
Thanks @apennell !

I must've had a typo somewhere as I seem to have got it working now...

Here is a [JSFiddle](https://jsfiddle.net/adriangibbons/zxob8nj3/) just in case anyone in future is interested :)
