### ISSUE TITLE
Styling independent from .popover class

### ISSUE THREAD

**Issue by danielsedlacek** [sorich87/bootstrap-tour#719]
Thanks for this phenomenal little library. 

I need to make the tour independent from the bootstrap .popover classes, but the classes in the template are used as selectors.

When I change the "popover-title" class to something else ("popover-title2") the title will not be populated. I have tried to change the step property to "title2" but it did not help.

I do not understand how are the step properties assigned to the template.

**Comment by IGreatlyDislikeJavascript** [comment]
It's not that the title isn't populated by tour, it's that bootstrap popover expects to find a DOM element with class = popover-title. When it doesn't, because you've removed it by changing the class, the title doesn't appear. The actual "content" is controlled by _showPopover() :

	$element.popover({
									placement: shouldAddSmart ? "auto " + step.placement : step.placement,
									trigger: 'manual',
									title: title,
									content: content,
									html: true,
									animation: step.animation,
									container: step.container,
									template: step.template,
									selector: step.element
								}).popover('show');

So it's actually nothing to do with tour, it's bootstrap.

**Comment by danielsedlacek** [comment]
Thank you, I have realized the popover is actually created by Bootstrap, not by this library. Thank you for your help.
